version: '3.8'

services:
  classic:
    image: ghcr.io/kernelkit/demo:latest
    build:
      context: ./classic
    environment:
      - DISPLAY=${DISPLAY}
      - SDL_AUDIODRIVER=pulseaudio
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
    network_mode: host
    stdin_open: true
    tty: true

  boring:
    image: ghcr.io/kernelkit/demo-boring:latest
    build:
      context: ./boring
    environment:
      - DISPLAY=${DISPLAY}
      - LATITUDE=${LATITUDE}
      - LONGITUDE=${LONGITUDE}
      - WEB_URL=${WEB_URL}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    stdin_open: true
    tty: true
